# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[░▒▓](#DFD7F7)\
$os\
[](fg:#DFD7F7 bg:#7e5ce5)\
$directory\
[](fg:#7e5ce5 bg:#423176)\
$git_branch\
$git_status\
[](fg:#423176 bg:#2C204E)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2C204E bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[os]
disabled = false
format = "[ $symbol ]($style)"
style = "fg:#37353E bg:#DFD7F7"

[os.symbols]
Windows = ""
Linux = ""
Ubuntu = ""


[directory]
style = "fg:#e3e5e5 bg:#7e5ce5"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
use_os_path_sep = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#423176"
format = '[[ $symbol $branch ](fg:#7e5ce5 bg:#423176)]($style)'

[git_status]
style = "bg:#423176"
format = '[[($all_status$ahead_behind )](fg:#7e5ce5 bg:#423176)]($style)'

[nodejs]
symbol = ""
style = "bg:#2C204E"
format = '[[ $symbol ($version) ](fg:#7e5ce5 bg:#2C204E)]($style)'

[rust]
symbol = ""
style = "bg:#2C204E"
format = '[[ $symbol ($version) ](fg:#7e5ce5 bg:#2C204E)]($style)'

[golang]
symbol = ""
style = "bg:#2C204E"
format = '[[ $symbol ($version) ](fg:#7e5ce5 bg:#2C204E)]($style)'

[php]
symbol = ""
style = "bg:#2C204E"
format = '[[ $symbol ($version) ](fg:#7e5ce5 bg:#2C204E)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = ''

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
format = ""
